# Generated by Django 3.2 on 2021-04-24 21:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('birth_date', models.DateField()),
                ('website', models.URLField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_title', models.CharField(max_length=200)),
                ('prefix', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('slug', models.SlugField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('prefix', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=2000)),
                ('slug', models.SlugField(max_length=250)),
                ('released_date', models.DateField()),
                ('cover_image', models.ImageField(upload_to='cover_image')),
                ('review', models.CharField(max_length=200)),
                ('asin', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{10}$')])),
                ('director', models.ManyToManyField(to='movie_app.Director')),
                ('genre', models.ManyToManyField(to='movie_app.Genre')),
                ('studio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie_app.studio')),
            ],
        ),
    ]
